# Generated by Django 4.1.7 on 2023-03-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cantante',
            old_name='anio',
            new_name='anio_de_nacimiento',
        ),
    ]
