# Generated by Django 4.1.7 on 2023-03-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('mejor_disco', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
